# Generated by Django 3.1.4 on 2020-12-19 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sauces', 'sauces'), ('desserts', 'desserts'), ('seafood', 'seafood'), ('biscuits', 'biscuits'), ('french_cheese', 'french_cheese'), ('pizza', 'pizza')], max_length=255),
        ),
    ]
