# Generated by Django 3.1.4 on 2020-12-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201219_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='substitut',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
