# Generated by Django 3.1.4 on 2021-02-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_substitut'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
